from typing import Optional, List, Dict, Any
from pydantic import BaseModel


class UserProfileInfoData(BaseModel):
    username: str


class UserProfileInfoResult(BaseModel):
    id: Optional[int]
    id_str: Optional[str]
    name: Optional[str]
    screen_name: Optional[str]
    location: Optional[str]
    profile_location: Optional[Dict[str, Any]]
    description: Optional[str]
    url: Optional[str]
    # entities: Optional[Entities]
    protected: Optional[bool]
    followers_count: Optional[int]
    fast_followers_count: Optional[int]
    normal_followers_count: Optional[int]
    friends_count: Optional[int]
    listed_count: Optional[int]
    created_at: Optional[str]
    favourites_count: Optional[int]
    utc_offset: Optional[int]
    time_zone: Optional[str]
    geo_enabled: Optional[bool]
    verified: Optional[bool]
    statuses_count: Optional[int]
    media_count: Optional[int]
    lang: Optional[str]
    # status: Optional[Status]
    contributors_enabled: Optional[bool]
    is_translator: Optional[bool]
    is_translation_enabled: Optional[bool]
    profile_background_color: Optional[str]
    profile_background_image_url: Optional[str]
    profile_background_image_url_https: Optional[str]
    profile_background_tile: Optional[bool]
    profile_image_url: Optional[str]
    profile_image_url_https: Optional[str]
    profile_banner_url: Optional[str]
    profile_link_color: Optional[str]
    profile_sidebar_border_color: Optional[str]
    profile_sidebar_fill_color: Optional[str]
    profile_text_color: Optional[str]
    profile_use_background_image: Optional[bool]
    has_extended_profile: Optional[bool]
    default_profile: Optional[bool]
    default_profile_image: Optional[bool]
    pinned_tweet_ids: Optional[List[int]]
    pinned_tweet_ids_str: Optional[List[str]]
    has_custom_timelines: Optional[bool]
    can_media_tag: Optional[bool]
    followed_by: Optional[bool]
    following: Optional[bool]
    follow_request_sent: Optional[bool]
    notifications: Optional[bool]
    advertiser_account_type: Optional[str]
    advertiser_account_service_levels: Optional[List[str]]
    business_profile_state: Optional[str]
    translator_type: Optional[str]
    withheld_in_countries: Optional[List[str]]
    require_some_consent: Optional[bool]
