# MAIN SETTINGS #
referral_code: C4ACD869
threads: 5
start_stealing_from_tree: 401000

mint_rpc_url: https://rpc.mintchain.io
op_rpc_url: https://mainnet.optimism.io

min_delay_before_start: 1  # seconds
max_delay_before_start: 2  # seconds

spin_turntable_by_percentage_of_energy: 20 # 0-100
shuffle_accounts: True  # True/False

comet_bridge_amount_min: 0.0001
comet_bridge_amount_max: 0.00013
comet_bridge_wallet: ""

